//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebSite.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バクニン省 (保税、一般倉庫).
        /// </summary>
        public static string bacninh {
            get {
                return ResourceManager.GetString("bacninh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 違反を報告する.
        /// </summary>
        public static string baocaosaipham {
            get {
                return ResourceManager.GetString("baocaosaipham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セーブに成功。 弊社へのフィードバックありがとうございます。.
        /// </summary>
        public static string baocaosaiphamthanhcong {
            get {
                return ResourceManager.GetString("baocaosaiphamthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service fee for domestic courier service.
        /// </summary>
        public static string baogiaphatnoidia {
            get {
                return ResourceManager.GetString("baogiaphatnoidia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service fee for international courier service.
        /// </summary>
        public static string baogiaphatquocte {
            get {
                return ResourceManager.GetString("baogiaphatquocte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDPRプライバシーポリシー.
        /// </summary>
        public static string cacdieukhoan {
            get {
                return ResourceManager.GetString("cacdieukhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 適用する方法.
        /// </summary>
        public static string cachthuc {
            get {
                return ResourceManager.GetString("cachthuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カンボジア支店.
        /// </summary>
        public static string Cambodia {
            get {
                return ResourceManager.GetString("Cambodia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バクニン支店.
        /// </summary>
        public static string chinhanhBacNinh {
            get {
                return ResourceManager.GetString("chinhanhBacNinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダナン支店.
        /// </summary>
        public static string chinhanhDaNang {
            get {
                return ResourceManager.GetString("chinhanhDaNang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドンナイ支店.
        /// </summary>
        public static string chinhanhDongNai {
            get {
                return ResourceManager.GetString("chinhanhDongNai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホーチミン本社.
        /// </summary>
        public static string chinhanhHCM {
            get {
                return ResourceManager.GetString("chinhanhHCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハノイ支店.
        /// </summary>
        public static string chinhanhHN {
            get {
                return ResourceManager.GetString("chinhanhHN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハイフォン事務所.
        /// </summary>
        public static string chinhanhHP {
            get {
                return ResourceManager.GetString("chinhanhHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連絡先.
        /// </summary>
        public static string chinhanhlienhe {
            get {
                return ResourceManager.GetString("chinhanhlienhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 個人情報保護方針.
        /// </summary>
        public static string chinhsachbaomat {
            get {
                return ResourceManager.GetString("chinhsachbaomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 販売方針.
        /// </summary>
        public static string chinhsachKH {
            get {
                return ResourceManager.GetString("chinhsachKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詳 細.
        /// </summary>
        public static string chitiet {
            get {
                return ResourceManager.GetString("chitiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コンサルタントのサポートのために支店を選択してください.
        /// </summary>
        public static string chonchinhanh {
            get {
                return ResourceManager.GetString("chonchinhanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 職名.
        /// </summary>
        public static string chucdanh {
            get {
                return ResourceManager.GetString("chucdanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受信者の署名を見る.
        /// </summary>
        public static string chuky {
            get {
                return ResourceManager.GetString("chuky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string chuyenphat {
            get {
                return ResourceManager.GetString("chuyenphat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to トラック約款.
        /// </summary>
        public static string condition {
            get {
                return ResourceManager.GetString("condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sgx(日本向け国際宅配便).
        /// </summary>
        public static string CPN_SGX {
            get {
                return ResourceManager.GetString("CPN_SGX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在、すべてのスタッフが忙しい、メッセージを残してください！.
        /// </summary>
        public static string CSbusy {
            get {
                return ResourceManager.GetString("CSbusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この期間は料金が発生されていません.
        /// </summary>
        public static string cuocphatsinh {
            get {
                return ResourceManager.GetString("cuocphatsinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上記送達電荷を一時的に計算されます。.
        /// </summary>
        public static string cuoctamtinh {
            get {
                return ResourceManager.GetString("cuoctamtinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顧客.
        /// </summary>
        public static string cus {
            get {
                return ResourceManager.GetString("cus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特徴.
        /// </summary>
        public static string dactrung {
            get {
                return ResourceManager.GetString("dactrung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ベトナムの外資系企業では唯一総合物流全免許、輸出入通関、国際航空海上輸送、トラック、一般倉庫、CFS倉庫、保税倉庫を取得しており、 高い輸送品質を提供することで信頼を得ています。.
        /// </summary>
        public static string dactrung_detail {
            get {
                return ResourceManager.GetString("dactrung_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANANG BRANCH.
        /// </summary>
        public static string danang {
            get {
                return ResourceManager.GetString("danang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Sea/Air Freight Forwarding, Local Transportation, Customs Clearance and Container Trucking).
        /// </summary>
        public static string danang_gom {
            get {
                return ResourceManager.GetString("danang_gom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 率と.
        /// </summary>
        public static string danhgia {
            get {
                return ResourceManager.GetString("danhgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オンライン注文.
        /// </summary>
        public static string dathangonline {
            get {
                return ResourceManager.GetString("dathangonline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詳細を見る.
        /// </summary>
        public static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 169 Dien Bien Phu Street, Ward 15,.
        /// </summary>
        public static string diachi_DBP1 {
            get {
                return ResourceManager.GetString("diachi_DBP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binh Thanh District, Ho Chi Minh City, Vietnam.
        /// </summary>
        public static string diachi_DBP2 {
            get {
                return ResourceManager.GetString("diachi_DBP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 87 Truong Son Street, Ward 2, Tan Binh District, HCMC., Vietnam.
        /// </summary>
        public static string diachi_truongson {
            get {
                return ResourceManager.GetString("diachi_truongson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot B1-10, B1-11, B1-12 Nguyen Phuc Street, Danang Aquaculture Service Industrial Park,.
        /// </summary>
        public static string diachidanang {
            get {
                return ResourceManager.GetString("diachidanang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tho Quang Ward, Son Tra District, Danang City, Vietnam..
        /// </summary>
        public static string diachidanang_tiep {
            get {
                return ResourceManager.GetString("diachidanang_tiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 169 Dien Bien Phu Street, Ward 15, Binh Thanh District, Ho Chi Minh City, Vietnam.
        /// </summary>
        public static string diachidienbienphu {
            get {
                return ResourceManager.GetString("diachidienbienphu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot B1-10, B1-11, B1-12 Nguyen Phuc Street, Danang Aquaculture Service Industrial Park, Tho Quang Ward, Son Tra District, Danang City, Vietnam..
        /// </summary>
        public static string diachiDN {
            get {
                return ResourceManager.GetString("diachiDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street No. 6, Nhon Trach 3 Industrial Park -Phase 2,.
        /// </summary>
        public static string diachiDongNai1 {
            get {
                return ResourceManager.GetString("diachiDongNai1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Tho Ward, Nhon Trach District, Dong Nai Province, Vietnam..
        /// </summary>
        public static string diachiDongNai2 {
            get {
                return ResourceManager.GetString("diachiDongNai2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03 Floor, MHDI Apartment, 60 Hoang Quoc Viet Street, Nghia Do Ward, Cau Giay District, Hanoi City, Vietnam.
        /// </summary>
        public static string diachihanoi {
            get {
                return ResourceManager.GetString("diachihanoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km 12 National Road No.5,
        ///Nomura Industrial Zone.
        /// </summary>
        public static string diachiHP1 {
            get {
                return ResourceManager.GetString("diachiHP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area, Hai Phong City, Vietnam.
        /// </summary>
        public static string diachiHP2 {
            get {
                return ResourceManager.GetString("diachiHP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit 1-2-3, Block 19, Lot 66 VSIP, .
        /// </summary>
        public static string diachiTuSon1 {
            get {
                return ResourceManager.GetString("diachiTuSon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phu Chan, Tu Son, Bac Ninh, Vietnam.
        /// </summary>
        public static string diachiTuSon2 {
            get {
                return ResourceManager.GetString("diachiTuSon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot D, Que Vo Industrial Park,.
        /// </summary>
        public static string diachiVPQueVo1 {
            get {
                return ResourceManager.GetString("diachiVPQueVo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que Vo District, Bac Ninh Province, Vietnam.
        /// </summary>
        public static string diachiVPQueVo2 {
            get {
                return ResourceManager.GetString("diachiVPQueVo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 場所.
        /// </summary>
        public static string diadiem {
            get {
                return ResourceManager.GetString("diadiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サービス一覧.
        /// </summary>
        public static string dichvu {
            get {
                return ResourceManager.GetString("dichvu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エクスプレスサービス.
        /// </summary>
        public static string dichvuchuyenphat {
            get {
                return ResourceManager.GetString("dichvuchuyenphat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダナン支店.
        /// </summary>
        public static string DNbranch {
            get {
                return ResourceManager.GetString("DNbranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引越サービス.
        /// </summary>
        public static string donchuyen {
            get {
                return ResourceManager.GetString("donchuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string donchuyentiep {
            get {
                return ResourceManager.GetString("donchuyentiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 閉じる.
        /// </summary>
        public static string dong {
            get {
                return ResourceManager.GetString("dong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing regulation of documents and goods.
        /// </summary>
        public static string donggoihh {
            get {
                return ResourceManager.GetString("donggoihh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONG NAI BRANCH.
        /// </summary>
        public static string DongNai {
            get {
                return ResourceManager.GetString("DongNai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引越しサービス(海外お引越し、ベトナム国内お引越し).
        /// </summary>
        public static string donnhavp {
            get {
                return ResourceManager.GetString("donnhavp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申込書.
        /// </summary>
        public static string donUT {
            get {
                return ResourceManager.GetString("donUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2MB未満のファイルをアップロード.
        /// </summary>
        public static string dungluongbe {
            get {
                return ResourceManager.GetString("dungluongbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 海上輸送サービス (輸出、輸入).
        /// </summary>
        public static string duongbien {
            get {
                return ResourceManager.GetString("duongbien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to トラック運送サービス.
        /// </summary>
        public static string duongbo {
            get {
                return ResourceManager.GetString("duongbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名 (2019年05月）.
        /// </summary>
        public static string dvnhanvien {
            get {
                return ResourceManager.GetString("dvnhanvien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 倉庫サービス.
        /// </summary>
        public static string dvukhobai {
            get {
                return ResourceManager.GetString("dvukhobai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メール連絡先.
        /// </summary>
        public static string emaillienlac {
            get {
                return ResourceManager.GetString("emaillienlac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a branch for consultants&apos; support.
        /// </summary>
        public static string errchonCNdehotro {
            get {
                return ResourceManager.GetString("errchonCNdehotro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value added services of domestic postal.
        /// </summary>
        public static string gtgtnoidia {
            get {
                return ResourceManager.GetString("gtgtnoidia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送信.
        /// </summary>
        public static string gui {
            get {
                return ResourceManager.GetString("gui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAI PHONG OFFICE.
        /// </summary>
        public static string haiphong {
            get {
                return ResourceManager.GetString("haiphong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通関サービス (輸出、輸入).
        /// </summary>
        public static string haiquan {
            get {
                return ResourceManager.GetString("haiquan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航空輸送サービス (輸出、輸入).
        /// </summary>
        public static string hangkhong {
            get {
                return ResourceManager.GetString("hangkhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効期限.
        /// </summary>
        public static string hannop {
            get {
                return ResourceManager.GetString("hannop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HANOI BRANCH.
        /// </summary>
        public static string HaNoi {
            get {
                return ResourceManager.GetString("HaNoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホーチミン支店.
        /// </summary>
        public static string HCMbranch {
            get {
                return ResourceManager.GetString("HCMbranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 興味のある候補者は、「適用」ボタンをクリックして履歴書を人事部に送信してください。.
        /// </summary>
        public static string HDtuyendung {
            get {
                return ResourceManager.GetString("HDtuyendung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハノイ支店.
        /// </summary>
        public static string HNbranch {
            get {
                return ResourceManager.GetString("HNbranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required document to be enclosed with goods.
        /// </summary>
        public static string hoadonchungtu {
            get {
                return ResourceManager.GetString("hoadonchungtu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顧客に手数料を返却する.
        /// </summary>
        public static string hoancuoc {
            get {
                return ResourceManager.GetString("hoancuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホーチミン (リンチュン CFS、保税、一般倉庫).
        /// </summary>
        public static string hochiminh {
            get {
                return ResourceManager.GetString("hochiminh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尊名.
        /// </summary>
        public static string hoten {
            get {
                return ResourceManager.GetString("hoten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サポート.
        /// </summary>
        public static string hotro {
            get {
                return ResourceManager.GetString("hotro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 問い合わせ.
        /// </summary>
        public static string khieunai {
            get {
                return ResourceManager.GetString("khieunai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 倉庫サービス.
        /// </summary>
        public static string khobai {
            get {
                return ResourceManager.GetString("khobai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFS 倉庫.
        /// </summary>
        public static string khoCFS {
            get {
                return ResourceManager.GetString("khoCFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検針＆検品エリア.
        /// </summary>
        public static string khokiemkim {
            get {
                return ResourceManager.GetString("khokiemkim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冷蔵＆冷凍倉庫.
        /// </summary>
        public static string kholanh {
            get {
                return ResourceManager.GetString("kholanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在、求人情報はありません。後で戻ってください。.
        /// </summary>
        public static string khongcotinTD {
            get {
                return ResourceManager.GetString("khongcotinTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この郵便番号に関する情報はありません。郵便番号を再入力してください.
        /// </summary>
        public static string khongtimthayvandon {
            get {
                return ResourceManager.GetString("khongtimthayvandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 危険品倉庫.
        /// </summary>
        public static string khonguyhiem {
            get {
                return ResourceManager.GetString("khonguyhiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一般倉庫.
        /// </summary>
        public static string khothuong {
            get {
                return ResourceManager.GetString("khothuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to トゥーソン事務所、保税倉庫.
        /// </summary>
        public static string khoTuSon {
            get {
                return ResourceManager.GetString("khoTuSon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検品・検針業務.
        /// </summary>
        public static string kiemkim {
            get {
                return ResourceManager.GetString("kiemkim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検品業務、検針業務.
        /// </summary>
        public static string kiemkimkiempham {
            get {
                return ResourceManager.GetString("kiemkimkiempham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 経験.
        /// </summary>
        public static string kinhnghiem {
            get {
                return ResourceManager.GetString("kinhnghiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （10 桁もしくは 12 桁の半角数字）.
        /// </summary>
        public static string kyso {
            get {
                return ResourceManager.GetString("kyso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to お問い合わせ.
        /// </summary>
        public static string lienhe {
            get {
                return ResourceManager.GetString("lienhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ご不明な点がありましたら、小切手手数料部門にお問い合わせください.
        /// </summary>
        public static string lienhecuoc {
            get {
                return ResourceManager.GetString("lienhecuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linh Trung Warehouse.
        /// </summary>
        public static string linhtrung {
            get {
                return ResourceManager.GetString("linhtrung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サービスの種類.
        /// </summary>
        public static string loaihinhdichvu {
            get {
                return ResourceManager.GetString("loaihinhdichvu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私たちにメッセージを残してください！.
        /// </summary>
        public static string loinhan {
            get {
                return ResourceManager.GetString("loinhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 給料.
        /// </summary>
        public static string luong {
            get {
                return ResourceManager.GetString("luong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顧客コード.
        /// </summary>
        public static string maKH {
            get {
                return ResourceManager.GetString("maKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 郵便番号.
        /// </summary>
        public static string mavandon {
            get {
                return ResourceManager.GetString("mavandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 郵便番号は空白にできません。 郵便番号を再入力してください.
        /// </summary>
        public static string mess_vandon {
            get {
                return ResourceManager.GetString("mess_vandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string motachinhsachbh {
            get {
                return ResourceManager.GetString("motachinhsachbh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕事内容.
        /// </summary>
        public static string motacv {
            get {
                return ResourceManager.GetString("motacv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当の支店を選択してください.
        /// </summary>
        public static string msgCompany {
            get {
                return ResourceManager.GetString("msgCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレスを入力してください.
        /// </summary>
        public static string msgEmail {
            get {
                return ResourceManager.GetString("msgEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あなたの名前は空白であってはなりません.
        /// </summary>
        public static string msgHoten {
            get {
                return ResourceManager.GetString("msgHoten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コンテンツは空にできません.
        /// </summary>
        public static string msgMess {
            get {
                return ResourceManager.GetString("msgMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードを入力してください.
        /// </summary>
        public static string msgPass {
            get {
                return ResourceManager.GetString("msgPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連絡先電話番号を入力してください.
        /// </summary>
        public static string msgPhone {
            get {
                return ResourceManager.GetString("msgPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイトルは空白にできません.
        /// </summary>
        public static string msgSubject {
            get {
                return ResourceManager.GetString("msgSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー名を入力してください.
        /// </summary>
        public static string msgUser {
            get {
                return ResourceManager.GetString("msgUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ベトナム～日本・海外へお引越しされるお客様やベトナム国内でお引越しされるお客様のお荷物を安全・確実・丁寧にお取り扱いさせて頂きます。お客様のお手を煩わせる事なく大切にされているお皿1枚から大型の家具まで、当社引越し専門のスタッフが責任を持って梱包させて頂いております。
        ///品質第一、経験豊富な日本人担当者が最適なプランをご提案させて頂きます。.
        /// </summary>
        public static string ND_donchuyen {
            get {
                return ResourceManager.GetString("ND_donchuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG 佐川ベトナムでは、佐川急便で培ったノウハウを生かし、ベトナム国内トラック輸送 （ハノイ～ホーチミン間の長距離輸送から市内配送まで）、クロスボーダートラック輸送 （ベトナム⇔タイ、ラオス、カンボジア）をご提案させていただいております。.
        /// </summary>
        public static string ND_duongbo {
            get {
                return ResourceManager.GetString("ND_duongbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG 佐川ベトナムでは、輸出入手続が煩雑なベトナムにおいて、豊富な経験を活かし、迅速確実にお客様の輸出入通関手続の代行業務をさせていただいております。.
        /// </summary>
        public static string ND_haiquan {
            get {
                return ResourceManager.GetString("ND_haiquan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG 佐川ベトナムでは、佐川グローバルロジスティクスのノウハウを活かし、ベトナム主要都市で保税倉庫、CFS倉庫、一般倉庫の運営をさせていただいております。.
        /// </summary>
        public static string ND_khobai {
            get {
                return ResourceManager.GetString("ND_khobai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG 佐川ベトナムでは、アパレル会社様のご要望にお答えし、検品・検針作業を行っております。お客様のご要望に合わせ出張検品も対応させていただいております。.
        /// </summary>
        public static string ND_kiemkim {
            get {
                return ResourceManager.GetString("ND_kiemkim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG 佐川ベトナムではお客様のご要望にあわせオーダーメードで物流を組み立てます。重量物の梱包輸送、3PL物流のご提案、お客様のお取引先へのJIT（ジャストインタイム)納品なども行っております。
        ///物流でお困りの場合は、経験豊富なSG 佐川ベトナムへ是非ご相談下さい。.
        /// </summary>
        public static string ND_trienkhai {
            get {
                return ResourceManager.GetString("ND_trienkhai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ndSGX {
            get {
                return ResourceManager.GetString("ndSGX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会社設立日.
        /// </summary>
        public static string ngaylap {
            get {
                return ResourceManager.GetString("ngaylap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保税倉庫.
        /// </summary>
        public static string ngoaiquan {
            get {
                return ResourceManager.GetString("ngoaiquan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会話を開始するメッセージ。.
        /// </summary>
        public static string nhantin {
            get {
                return ResourceManager.GetString("nhantin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 運送状番号を入力してく.
        /// </summary>
        public static string nhapsodonhang {
            get {
                return ResourceManager.GetString("nhapsodonhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 運送状番号を入力してく.
        /// </summary>
        public static string nhapvandon {
            get {
                return ResourceManager.GetString("nhapvandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ニョンチャック倉庫.
        /// </summary>
        public static string nhontrach {
            get {
                return ResourceManager.GetString("nhontrach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 国内配送ホットライン.
        /// </summary>
        public static string noidia {
            get {
                return ResourceManager.GetString("noidia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG佐川ベトナムでは、ベトナムの主要港（ハイフォン港、ホーチミン港、ダナン港）において、輸出入の海上貨物輸送サービスの手配を行っております。コンテナ単位の輸送から、LCL貨物の輸送、特殊コンテナ輸送もご提案させていただいております。
        ///※LCL･･･Less than Container Loadの略称で複数の荷主貨物が、ひとつのコンテナに混載して輸送する方法。.
        /// </summary>
        public static string noidungBien {
            get {
                return ResourceManager.GetString("noidungBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG 佐川ベトナムでは、世界各国向けに輸出航空貨物の手配をさせていただいており、また、世界各国からベトナム向けの輸入航空貨物も手配いたします。直行便、経由便も含めお客様の幅広いニーズに合わせた航空貨物輸送サービスをご提案させていただいております。.
        /// </summary>
        public static string noidungHK {
            get {
                return ResourceManager.GetString("noidungHK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕事をする.
        /// </summary>
        public static string nopdon {
            get {
                return ResourceManager.GetString("nopdon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私たちのサービス.
        /// </summary>
        public static string ourservices {
            get {
                return ResourceManager.GetString("ourservices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 国内エクスプレスサービス.
        /// </summary>
        public static string phatnoidia {
            get {
                return ResourceManager.GetString("phatnoidia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 国際エクスプレスサービス.
        /// </summary>
        public static string phatquocte {
            get {
                return ResourceManager.GetString("phatquocte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Departments: Board of Director, Administration, Accounting, Removal,Custom Clearance,SeaFreight ,e-Global, Sales).
        /// </summary>
        public static string phongbanDBP {
            get {
                return ResourceManager.GetString("phongbanDBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索キーワードを入力してください.
        /// </summary>
        public static string presskey {
            get {
                return ResourceManager.GetString("presskey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International courier process.
        /// </summary>
        public static string qtrphatquocte {
            get {
                return ResourceManager.GetString("qtrphatquocte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic courier process.
        /// </summary>
        public static string qtrphattrongnuoc {
            get {
                return ResourceManager.GetString("qtrphattrongnuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damages Compensation &amp; Complaints Resolve.
        /// </summary>
        public static string qtrtrachnhiem {
            get {
                return ResourceManager.GetString("qtrtrachnhiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules for cargo of domestic courier service.
        /// </summary>
        public static string qtrvanchuyennoidia {
            get {
                return ResourceManager.GetString("qtrvanchuyennoidia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules for cargo international courier service.
        /// </summary>
        public static string qtrvanchuyenquocte {
            get {
                return ResourceManager.GetString("qtrvanchuyenquocte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process delivery parcel handling.
        /// </summary>
        public static string qtrxulybpbk {
            get {
                return ResourceManager.GetString("qtrxulybpbk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que Vo Warehouse.
        /// </summary>
        public static string quevo {
            get {
                return ResourceManager.GetString("quevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一般的な規制.
        /// </summary>
        public static string quydinhchuyenphat {
            get {
                return ResourceManager.GetString("quydinhchuyenphat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 海上貨物サービスの規制.
        /// </summary>
        public static string quydinhvtbien {
            get {
                return ResourceManager.GetString("quydinhvtbien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウェブサイトのご利用について.
        /// </summary>
        public static string quytrinhsudung {
            get {
                return ResourceManager.GetString("quytrinhsudung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電番.
        /// </summary>
        public static string sdt {
            get {
                return ResourceManager.GetString("sdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連絡先電話.
        /// </summary>
        public static string sdtlienhe {
            get {
                return ResourceManager.GetString("sdtlienhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーチ.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 佐川急便ベトナム有限会社.
        /// </summary>
        public static string sev {
            get {
                return ResourceManager.GetString("sev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1997年 6月 12日.
        /// </summary>
        public static string sevngaylap {
            get {
                return ResourceManager.GetString("sevngaylap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG佐川ベトナム有限会社.
        /// </summary>
        public static string sgv {
            get {
                return ResourceManager.GetString("sgv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015年 05月 01日.
        /// </summary>
        public static string sgvngaylap {
            get {
                return ResourceManager.GetString("sgvngaylap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 国内・国際エクスプレスサービス.
        /// </summary>
        public static string Sgx {
            get {
                return ResourceManager.GetString("Sgx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORWARDING約款.
        /// </summary>
        public static string SGXStandard {
            get {
                return ResourceManager.GetString("SGXStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEAD OFFICE.
        /// </summary>
        public static string sochinh {
            get {
                return ResourceManager.GetString("sochinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot 117 Industrial Park in Sai Gon- Linh Trung Export Processing Zone, Thu Duc District, HCMC, Vietnam.
        /// </summary>
        public static string sochinh_address {
            get {
                return ResourceManager.GetString("sochinh_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サイトマップ.
        /// </summary>
        public static string sodoweb {
            get {
                return ResourceManager.GetString("sodoweb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 社員数.
        /// </summary>
        public static string soluongnv {
            get {
                return ResourceManager.GetString("soluongnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGX約款.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状態.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サポート.
        /// </summary>
        public static string supp {
            get {
                return ResourceManager.GetString("supp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オンラインサポート.
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string taovandon {
            get {
                return ResourceManager.GetString("taovandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この求人はベトナム語のみをサポートしています.
        /// </summary>
        public static string TDsupport {
            get {
                return ResourceManager.GetString("TDsupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顧客.
        /// </summary>
        public static string tenKH {
            get {
                return ResourceManager.GetString("tenKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取り付け.
        /// </summary>
        public static string tepdinhkem {
            get {
                return ResourceManager.GetString("tepdinhkem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 貨 物 追 跡.
        /// </summary>
        public static string theodoidonhang {
            get {
                return ResourceManager.GetString("theodoidonhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交渉可能.
        /// </summary>
        public static string thoathuan {
            get {
                return ResourceManager.GetString("thoathuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メッセージ本文.
        /// </summary>
        public static string thongdiep {
            get {
                return ResourceManager.GetString("thongdiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連絡先と申込書.
        /// </summary>
        public static string thongtinlienhe {
            get {
                return ResourceManager.GetString("thongtinlienhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通関サービス.
        /// </summary>
        public static string thutuchaiquan {
            get {
                return ResourceManager.GetString("thutuchaiquan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality postal service standard.
        /// </summary>
        public static string tieuchuanchatluong {
            get {
                return ResourceManager.GetString("tieuchuanchatluong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 題名.
        /// </summary>
        public static string tieude {
            get {
                return ResourceManager.GetString("tieude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時間.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string TimKiem {
            get {
                return ResourceManager.GetString("TimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 郵便番号の検索.
        /// </summary>
        public static string timkiemvandon {
            get {
                return ResourceManager.GetString("timkiemvandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 国内貨物はこ ち ら.
        /// </summary>
        public static string timquocnoi {
            get {
                return ResourceManager.GetString("timquocnoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 海外貨物はこ ち ら.
        /// </summary>
        public static string timquocte {
            get {
                return ResourceManager.GetString("timquocte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 州へ.
        /// </summary>
        public static string tinhden {
            get {
                return ResourceManager.GetString("tinhden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 州から.
        /// </summary>
        public static string tinhdi {
            get {
                return ResourceManager.GetString("tinhdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドンナイ省　（ニョンチャック倉庫：保税倉庫、冷蔵＆冷凍倉庫、一般倉庫、危険品倉庫）.
        /// </summary>
        public static string tinhdongnai {
            get {
                return ResourceManager.GetString("tinhdongnai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新着情報.
        /// </summary>
        public static string tintuc {
            get {
                return ResourceManager.GetString("tintuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG佐川ベトナム及び佐川急便ベトナム有限会社 は SGホールディングス株式会社のベトナム現地法人として、ベトナムの総合物流ソリューションをご提供しております。.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チェックコスト.
        /// </summary>
        public static string tracuoconline {
            get {
                return ResourceManager.GetString("tracuoconline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tracuu {
            get {
                return ResourceManager.GetString("tracuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 郵便番号を調べる.
        /// </summary>
        public static string tracuuBPBK {
            get {
                return ResourceManager.GetString("tracuuBPBK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホーム.
        /// </summary>
        public static string trangchu {
            get {
                return ResourceManager.GetString("trangchu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロジェクト貨物.
        /// </summary>
        public static string trienkhaihangduan {
            get {
                return ResourceManager.GetString("trienkhaihangduan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロジェクトカーゴ.
        /// </summary>
        public static string trienkhaihanghoa {
            get {
                return ResourceManager.GetString("trienkhaihanghoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Office :.
        /// </summary>
        public static string trusochinh {
            get {
                return ResourceManager.GetString("trusochinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会社の情報.
        /// </summary>
        public static string ttcty {
            get {
                return ResourceManager.GetString("ttcty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顧客コードとパスワードを使用してシステムにログインし、ホット料金を確認し、過去の期間やその他のユーティリティを探してください。 顧客IDがない場合は、コールセンター1900 54 55 38（内線4008）に連絡して指示を求め、顧客コードを作成してください。.
        /// </summary>
        public static string ttIndex {
            get {
                return ResourceManager.GetString("ttIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 募集情報.
        /// </summary>
        public static string ttTD {
            get {
                return ResourceManager.GetString("ttTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キーワード.
        /// </summary>
        public static string tukhoa {
            get {
                return ResourceManager.GetString("tukhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu Son Warehouse.
        /// </summary>
        public static string tuson {
            get {
                return ResourceManager.GetString("tuson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 採用情報.
        /// </summary>
        public static string tuyendung {
            get {
                return ResourceManager.GetString("tuyendung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 施す.
        /// </summary>
        public static string ungtuyen {
            get {
                return ResourceManager.GetString("ungtuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常に適用されます！.
        /// </summary>
        public static string UTsucc {
            get {
                return ResourceManager.GetString("UTsucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容を入力してください.
        /// </summary>
        public static string vadnoidung {
            get {
                return ResourceManager.GetString("vadnoidung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップロードファイルを選択してください.
        /// </summary>
        public static string vadTep {
            get {
                return ResourceManager.GetString("vadTep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 職種.
        /// </summary>
        public static string vitri {
            get {
                return ResourceManager.GetString("vitri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dien Bien Phu Office:.
        /// </summary>
        public static string VP_DBP {
            get {
                return ResourceManager.GetString("VP_DBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truong Son Office:.
        /// </summary>
        public static string VP_TruongSon {
            get {
                return ResourceManager.GetString("VP_TruongSon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bac Ninh Branch.
        /// </summary>
        public static string vpBacNinh {
            get {
                return ResourceManager.GetString("vpBacNinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIEN BIEN PHU OFFICE.
        /// </summary>
        public static string vpdienbienphu {
            get {
                return ResourceManager.GetString("vpdienbienphu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai Phong Office.
        /// </summary>
        public static string vpHaiPhong {
            get {
                return ResourceManager.GetString("vpHaiPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クエボ事務所、保税一般倉庫.
        /// </summary>
        public static string VPQueVo {
            get {
                return ResourceManager.GetString("VPQueVo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR FREIGHT OFFICE.
        /// </summary>
        public static string VPvtaiHK {
            get {
                return ResourceManager.GetString("VPvtaiHK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 87 Truong Son Street, Ward 2, Tan Binh District, HCMC., Vietnam.
        /// </summary>
        public static string VPvtaiHK_diachi {
            get {
                return ResourceManager.GetString("VPvtaiHK_diachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Close to Tan Son Nhat International Airport).
        /// </summary>
        public static string VPvtaiHK_ghichu {
            get {
                return ResourceManager.GetString("VPvtaiHK_ghichu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 海上貨物輸送サービス.
        /// </summary>
        public static string vtaiBien {
            get {
                return ResourceManager.GetString("vtaiBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to トラック配送サービス.
        /// </summary>
        public static string vtaiBo {
            get {
                return ResourceManager.GetString("vtaiBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航空貨物輸送サービス.
        /// </summary>
        public static string vtaiHK {
            get {
                return ResourceManager.GetString("vtaiHK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to もっと見る.
        /// </summary>
        public static string xemthem {
            get {
                return ResourceManager.GetString("xemthem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 続く.
        /// </summary>
        public static string xemtiep {
            get {
                return ResourceManager.GetString("xemtiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ク リア.
        /// </summary>
        public static string Xoa {
            get {
                return ResourceManager.GetString("Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling parcel without receiver.
        /// </summary>
        public static string xulybp {
            get {
                return ResourceManager.GetString("xulybp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メール.
        /// </summary>
        public static string youremail {
            get {
                return ResourceManager.GetString("youremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to お名前 (必須）.
        /// </summary>
        public static string yourname {
            get {
                return ResourceManager.GetString("yourname", resourceCulture);
            }
        }
    }
}
